project:
  type: website
  output-dir: docs

website:
  title: "Solitary Crow's Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Blog/index.qmd
        text: Blog
      - href: books.qmd
        text: books
    tools:
      - icon: github
      - href: https://github.com

  page-footer: 
    left: "Copyright 2025, solitary_crow"
    right:
      - icon: github
        href: https://github.com
      - icon: twitter
        href: https://twitter.com
      - icon: reddit
        href: https://reddit.com
      - icon: linkedin
        href: https://linkedin.com

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



